sudo: required
services:
  - docker

before_install:
  - docker build -t skbusi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skbusi/react-test npm run test -- --coverage

after_success:
  - docker build -t skbusi/multi-client ./client
  - docker build -t skbusi/multi-worker ./worker
  - docker build -t skbusi/multi-server ./server
  - docker build -t skbusi/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push skbusi/multi-client
  - docker push skbusi/multi-worker
  - docker push skbusi/multi-ngnix
  - docker push skbusi/multi-server



#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-sbusi-frontend"
#  env: "DockerSbusiFrontend-env"
#  bucket_name: "elasticbeanstalk-us-west-2-857414306949"
#  bucket_path: "docker-sbusi-frontend"
#  on:
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
