sudo: required
services:
  - docker

before_install:
  - docker build -t skbusi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skbusi/react-test npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-sbusi-frontend"
#  env: "DockerSbusiFrontend-env"
#  bucket_name: "elasticbeanstalk-us-west-2-857414306949"
#  bucket_path: "docker-sbusi-frontend"
#  on:
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
